dataset_conf:
  min_duration: 0
  max_duration: 12
  do_vad: False
  sample_rate: 32000
  use_dB_normalization: True
  # Normalize the volume decibel value of audio for volume normalization
  target_dB: -20
  train_list: '/path/to/train_list.txt'
  test_list: '/path/to/test_list.txt'
  label_list_path: '/path/to/label_list.txt'
  eval_conf:
    batch_size: 16
    max_duration: 12
  dataLoader:
    batch_size: 16
    num_workers: 24
    # whether want to discard the last sample
    drop_last: True

preprocess_conf:
  #Audio preprocessing methods：MelSpectrogram、MFCC、Fbank
  feature_method: 'Fbank'
  method_args:
    sample_frequency: 32000
    num_mel_bins: 40
    frame_length: 25
    frame_shift: 10
    low_freq: 0.0
    high_freq: 3000.0

    
optimizer_conf:
  # optimization:Adam
  optimizer: 'Adam'
  # The size of the initial learning rate
  learning_rate: 0.0001
  weight_decay: !!float 1e-6
  # Learning rate decay function
  scheduler: 'WarmupCosineSchedulerLR'
  scheduler_args:
    min_lr: !!float 1e-6
    max_lr: 0.0001
    warmup_epoch: 5

model_conf:
  num_class: 2
  dropout: 0.1


train_conf:
  # Whether to enable automatic mixing accuracy
  enable_amp: False
  # whether to use the Pytorch 2.0 compiler
  use_compile: False
  loss_weight: [1.0, 5.0]
  # Number of training rounds
  max_epoch: 30
  log_interval: 10

use_model: 'DeepADN_PLUS'